global:
  scrape_interval: 10s
  evaluation_interval: 10s

# Load alert rules
rule_files:
  - "alert.rules.yml"

# Alertmanager connection
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "3.106.156.32:9093"

# Scrape the custom exporter
scrape_configs:
  - job_name: "sentiment-ml-exporter"
    static_configs:
      - targets: ["3.106.156.32:8000"]